export const projects = [
  {
    title: 'Political Search Engine',
    description: "This Ruby On Rails web application was built alongside three other Berkeley students and is a fully functional search engine. Powered by Google's Civic API, this app allows users to search for U.S. representatives from any region with a fully interactive map. Additionally, users can share opinions in the form of news articles, and can login via Github or Google.",
      image: '/images/political_search_engine.png',
      tags: ['Ruby On Rails', 'JavaScript', 'Google Civic API', 'HAML'],
    source: '',
    visit: 'https://peaceful-forest-42901.herokuapp.com/',
    suffix: '',
    id: 0,
    notClickable: true,
  },
  {
    title: 'Gitlet',
    description:"Utilizing Java's object-oriented nature as well as fundamental OOP design-patterns, this piece of software replicates the fundamental features of git, created entirely from scratch. This program enables the user to leverage command line arguments to add, commit, merge, and push (among many others) files in a local system. It is fully comprehensive and can safely and accurately store and track file changes. Image courtesy of ",
    image: '/images/gitlet_infinite.gif',
    tags: ['Java', 'Dropbox Paper'],
    source: '',
    visit: 'https://github.com/ryan-garay89/gitlet',
    suffix: <a href='https://dev.to/lydiahallie' target="_blank" style={{ color: '#3366BB', textDecoration: 'underline' }}>Lydia Hallie</a>,
    id: 1,
    notClickable: false,
  },
  {
    title: 'Political Polarization API',
    description: "Designed and researched alongside three fellow Berkeley students, this project was conceived as a means to measure discretely the levels of polarization resulting from various topics in U.S. politics. Our API utilizes natural language processing (NLP) to digest comments obtained by the NYT API, and scores them based on pre-determined heuristics.",
      image: '/images/news_polarization_proj.png',
      tags: ['Python', 'NYT API', 'TexBlob NLP API',],
    source: '',
    suffix: '',
    visit: 'https://docs.google.com/presentation/d/1LMb_jUPcWKwrauNmKpExkwkM-SVOc7pSoXc7nKdUQrE/edit?usp=sharing',
    id: 2,
    notClickable: true,
  },
  {
    title: 'NumC',
    description: "NumC is a matrix multiplication and manipulation module written in C and designed for use in Python. Very similar to the popular library 'Numpy,' NumC is fully importable from Python and allows the programmer to easily create, compute, and transform matrices using the methods provided by C code. Image courtesy of ",
    image: '/images/numc_infinite_cropped.gif',
    tags: ['C', 'Python'],
    source: '',
    suffix: <a href='https://devforum.roblox.com/t/how-multiply-matrices-in-a-special-way/1080273' target="_blank" style={{ color: '#3366BB', textDecoration: 'underline' }}>DevForum</a>,
    visit: 'https://google.com',
    id: 3,
    notClickable: true,
  },
  {
    title: 'BRSP Web App',
    description: "The Berkeley Reentry Student Program (BRSP) is a UC Berkeley org centered around helping non-traditional students re-enter the academic space. The web app requested and built by our team of five engineers allows BRSP students to check-in to the on-campus study space and access crucial program resources. The custom database we designed holds student and admin data, such as ID and email, and has been integrated with GoogleOauth2 for easy login. ",
    image: 'images/Seal_of_University_of_California,_Berkeley.svg.png',
    tags: ['Ruby On Rails', 'PostgresQL'],
    source: '',
    suffix: '',
    visit: 'https://github.com/ryan-garay89/berkeley-reentry-student-program',
    id: 4,
    notClickable: false,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Learned Java & Founded High School Coding Org', },
  { year: 2019, text: 'Accepted to UC Berkeley', },
  { year: 2020, text: 'Software Dev Intern @ CGI Inc. / Self-Taught React & MVC Framework', },
  { year: 2021, text: 'Software Eng Intern @ Coursera', },
  { year: 2022, text: 'SDE Intern @ Amazon', },
  { year: 2022, text: 'Accepted Full-Time Offer @ Amazon', },
];