export const projects = [
  {
    title: 'Political Search Engine',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/political_search_engine.png',
      tags: ['Ruby On Rails', 'JavaScript', 'Google Civi API', 'HAML'],
    source: 'https://google.com',
    visit: 'https://peaceful-forest-42901.herokuapp.com/',
    suffix: '',
    id: 0,
    notClickable: true,
  },
  {
    title: 'Gitlet',
    description:"you will be able to add to your portfolio. And trust me, e-commerce applications are impressive. Image courtesy of ",
    image: '/images/gitlet_infinite.gif',
    tags: ['Java', 'Dropbox Paper'],
    source: 'https://google.com',
    visit: 'https://google.com',
    suffix: <a href='https://dev.to/lydiahallie' style={{ color: '#3366BB', textDecoration: 'underline' }}>Lydia Hallie</a>,
    id: 1,
    notClickable: true,
  },
  {
    title: 'Political Polarization API',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/news_polarization_proj.png',
      tags: ['Python', 'NYT API', 'TexBlob NLP API',],
    source: 'https://google.com',
    suffix: '',
    visit: 'https://docs.google.com/presentation/d/1LMb_jUPcWKwrauNmKpExkwkM-SVOc7pSoXc7nKdUQrE/edit?usp=sharing',
    id: 2,
    notClickable: true,
  },
  {
    title: 'NumC',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/numc_infinite_cropped.gif',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    suffix: '',
    visit: 'https://google.com',
    id: 3,
    notClickable: true,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Learned Java & Founded High School Coding Org', },
  { year: 2019, text: 'Accepted to UC Berkeley', },
  { year: 2020, text: 'Software Dev Intern @ CGI Inc. / Self-Taught React & MVC Framework', },
  { year: 2021, text: 'Software Eng Intern @ Coursera', },
  { year: 2022, text: 'Accepted SDE Internship @ Amazon', },
];